[package]
name = "slahasher"
version = "0.3.11"
edition = "2024"
description = "Hashing functions"
license = "MIT"
hompage = "https://github.com/beamvex/slahasher"
authors = ["Robert Forster <robert.forster@beamvex.com>"]
repository = "https://github.com/beamvex/slahasher"
documentation = "https://docs.rs/slahasher"

[lib]
test = true

[dependencies]
slogger = "0.1.2"
base_xx = "0.6.1"
chrono = "0.4.34"
sha2 = "0.11.0-rc.5"
sha3 = "0.10.0" 
ripemd = "0.1.0"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
allow-expect-in-tests = "allow"


